{% set name = "xtb" %}
{% set version = "6.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/{{ name }}/archive/7127b05a041be4b3cce8d74540e63928f8ee2ed4.tar.gz
  sha256: 962dc12e9f6c6dbbbdad369cc5ed9d840c8f372217ac4fdfe8284d224e311ec8

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - meson >=0.51  # [not osx]
    - meson 0.51.*  # [osx]
    - ninja
  host:
    - libblas
    - liblapack
    - llvm-openmp  # [osx]
    - libgomp  # [linux and not aarch64]
  run:
    - libblas
    - liblapack


test:
  commands:
    - xtb --version

about:
  home: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/{{ name }}
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "COPYING"
    - "COPYING.LESSER"
  summary: 'Semiempirical Extended Tight-Binding Program Package'
  doc_url: https://{{ name }}-docs.readthedocs.io/
  dev_url: https://github.com/grimme-lab/{{ name }}

extra:
  recipe-maintainers:
    - awvwgk
